# Generated by Django 5.2.17 on 2026-10-03 23:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[core.validators.symbol_validator])),
                ('last_name', models.CharField(max_length=100, validators=[core.validators.symbol_validator])),
                ('email', models.EmailField(max_length=254)),
                ('desired_position', models.CharField(choices=[('FULL_STACK_DEV', 'Full-Stack Developer'), ('FRONT_END_DEV', 'Front-End Developer'), ('BACK_END_DEV', 'Back-End Developer'), ('MOBILE_DEV', 'Mobile App Developer'), ('GAME_DEV', 'Game Developer')], max_length=20)),
            ],
        ),
    ]
