# Generated by Django 5.2.17 on 2026-10-03 23:57

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[core.validators.symbol_validator])),
                ('last_name', models.CharField(max_length=100, validators=[core.validators.symbol_validator])),
                ('profession', models.CharField(choices=[('FULL_STACK_DEV', 'Full-Stack Developer'), ('FRONT_END_DEV', 'Front-End Developer'), ('BACK_END_DEV', 'Back-End Developer'), ('MOBILE_DEV', 'Mobile App Developer'), ('GAME_DEV', 'Game Developer')], max_length=20)),
                ('years_of_experience', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='employees/')),
                ('skills', models.ManyToManyField(blank=True, related_name='employees', to='employees.skill')),
            ],
        ),
    ]
