# Generated by Django 5.2.17 on 2026-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='img-def-not-ai.png', upload_to='employees/'),
        ),
    ]
