# Generated by Django 5.2.17 on 2026-10-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
