# Generated by Django 5.2.17 on 2026-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_task',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
