# Generated by Django 5.2.17 on 2026-10-09 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_current_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
