# Generated by Django 5.2.17 on 2026-10-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', 'Terrible'), ('2', 'Bad'), ('3', 'Ok'), ('4', 'Good'), ('5', 'Excellent')]),
        ),
    ]
