excuses = [
    "fixing something AI broke",
    "fixing something that was vibe coded",
    "fixing 404s",
    "fixing a bug AI introduced while fixing another bug",
    "fixing a 'quick fix' that broke 3 other things",
    "fixing the fix for the fix of the hotfix",
    "fixing merge conflicts nobody admits to creating",
    "fixing a deploy that worked yesterday",
    "fixing tests that pass only on Tuesdays",
    "fixing a button that does nothing",
    "fixing a CSS change that moved everything 2px",
    "fixing a regex nobody dares to touch",
    "fixing a production bug that doesn't reproduce locally",
    "fixing legacy code with no comments and no author",
    "fixing a prompt that worked perfectly yesterday",
    "fixing hallucinated imports",
    "fixing an API that AI invented",
    "fixing a migration that went sideways",
    "fixing a cron job that runs at the wrong time",
    "fixing CORS errors (again)",
    "fixing an environment variable that went missing",
    "fixing a feature nobody remembers asking for",
    "fixing a typo in the config that took down staging",
    "fixing 'it works on my machine'",
    "fixing a 500 error with an empty log",
    "fixing a bug that disappeared when someone looked at it",
    "Just being lazy"
]